#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    spt-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^spt\.ddev\.site$`)
      
      service: "spt-web-80"
      tls: false
      # middlewares:
      #   - "spt-redirectHttps"
    spt-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^spt\.ddev\.site$`)
      
      service: "spt-web-8025"
      tls: false
      # middlewares:
      #   - "spt-redirectHttps"
    spt-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^spt\.ddev\.site$`)
      
      service: "spt-xhgui-80"
      tls: false
      # middlewares:
      #   - "spt-redirectHttps"
    
    
    
    spt-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^spt\.ddev\.site$`)
      
      service: "spt-web-80"
      
      tls: true
      
    spt-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^spt\.ddev\.site$`)
      
      service: "spt-web-8025"
      
      tls: true
      
    
    spt-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^spt\.ddev\.site$`)
      
      service: "spt-xhgui-80"
      
      tls: true
      
    

  middlewares:
    spt-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    spt-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-spt-web:80
        
    spt-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-spt-web:8025
        
    
    
    spt-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-spt-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/spt.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/spt.key